# Generated by Django 5.1.15 on 2026-03-27 12:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_tenant_state_code"),
        ("products", "0002_product_gst_rate_product_hsn_code_bundle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("daily_avg_sales", models.FloatField()),
                ("days_of_stock_left", models.FloatField()),
                ("reorder_suggestion_qty", models.IntegerField()),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="products.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "forecast result",
                "verbose_name_plural": "forecast results",
                "ordering": ["days_of_stock_left"],
            },
        ),
    ]
