# Generated by Django 5.1.15 on 2026-04-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecastresult",
            name="days_of_stock_left",
            field=models.FloatField(null=True),
        ),
    ]
