# Generated by Django 5.1.15 on 2026-03-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="quantity_after",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="quantity_before",
            field=models.IntegerField(default=0),
        ),
    ]
