# Generated by Django 5.1.15 on 2026-03-27 08:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("order_received", "Order Received"),
                            ("sync_failure", "Sync Failure"),
                            ("po_overdue", "PO Overdue"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("message", models.TextField()),
                (
                    "related_object_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("related_object_id", models.UUIDField(blank=True, null=True)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
