# Generated by Django 5.1.15 on 2026-03-27 12:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_tenant_state_code"),
        ("alerts", "0001_initial"),
        ("products", "0002_product_gst_rate_product_hsn_code_bundle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alert",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="sent_via",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("whatsapp", "WhatsApp"),
                    ("in_app", "In-App"),
                ],
                default="in_app",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AlertSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_alerts_enabled", models.BooleanField(default=True)),
                ("whatsapp_alerts_enabled", models.BooleanField(default=False)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                (
                    "low_stock_threshold_override",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_settings",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "alert settings",
            },
        ),
    ]
