# Generated by Django 5.1.15 on 2026-03-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_tenant_state_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("growth", "Growth"),
                            ("pro", "Pro"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=50)),
                (
                    "price_monthly_inr",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "price_monthly_usd",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("stripe_price_id_inr", models.CharField(blank=True, max_length=100)),
                ("stripe_price_id_usd", models.CharField(blank=True, max_length=100)),
                ("max_skus", models.IntegerField()),
                ("max_channels", models.IntegerField()),
                ("max_locations", models.IntegerField()),
                ("max_users", models.IntegerField()),
                ("has_forecasting", models.BooleanField(default=False)),
                ("has_gst_reports", models.BooleanField(default=False)),
                ("has_whatsapp_alerts", models.BooleanField(default=False)),
                ("has_bundles", models.BooleanField(default=False)),
                ("has_api_access", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TenantSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("cancelled", "Cancelled"),
                            ("free", "Free"),
                        ],
                        default="trialing",
                        max_length=20,
                    ),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=100)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("trial_ends_at", models.DateTimeField(null=True)),
                ("current_period_end", models.DateTimeField(null=True)),
                ("cancelled_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.plan",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="accounts.tenant",
                    ),
                ),
            ],
        ),
    ]
