# Generated by Django 5.1.15 on 2026-03-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="state_code",
            field=models.CharField(
                default="09",
                help_text="2-digit India state code (e.g. 09 for UP, 27 for MH)",
                max_length=2,
            ),
        ),
    ]
