# Generated by Django 5.1.15 on 2026-03-27 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopifyStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shop_domain", models.CharField(max_length=255, unique=True)),
                ("access_token", models.CharField(max_length=255)),
                ("webhook_secret", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopify_stores",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChannelProductMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("shopify", "Shopify"), ("amazon", "Amazon")],
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="Shopify product_id or Amazon ASIN", max_length=100
                    ),
                ),
                ("external_variant_id", models.CharField(blank=True, max_length=100)),
                (
                    "external_inventory_item_id",
                    models.CharField(
                        blank=True, help_text="For inventory level sync", max_length=100
                    ),
                ),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_mappings",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "channel")},
            },
        ),
    ]
