# Generated by Django 5.1.15 on 2026-04-01 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_state_code'),
        ('channels_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_id', models.CharField(max_length=50)),
                ('seller_id', models.CharField(max_length=50)),
                ('refresh_token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('sync_inventory', models.BooleanField(default=True)),
                ('sync_orders', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_stores', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
